name: .NET Core CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

env:
  registryName : "pg2tlmdgnl5h4mpnpreg.azurecr.io"
  repositoryName : "techboost/dotnetcoreapp"
  dockerFolderPath: "Application/src/RazorPagesTestSample"
  tag : ${{ github.run_number  }}

jobs:
    build:
        
        runs-on: ubuntu-latest
        

        steps:
            
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
                dotnet-version: 6.0

        - name: Restore dependencies
          run: dotnet restore
          working-directory: ./Application/src/RazorPagesTestSample

        - name: Build
          run: dotnet build --no-restore
          working-directory: ./Application/src/RazorPagesTestSample

        - name: Test
          run: dotnet test --no-build --verbosity normal
          working-directory: ./Application/src/RazorPagesTestSample

        - name: Login to Docker registry
          run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
    
        - name: Build Docker image
          run: docker build -t ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }} ${{ env.dockerFolderPath }}
    
        - name: Push Docker image
          run: docker push ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }}
  
    deploydev:
  
          runs-on: ubuntu-latest
          needs: build
        
          steps:
              - name: 'Login via Azure CLI'
                uses: azure/login@v1
                with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}
        
              - uses: azure/webapps-deploy@v2
                with:
                  app-name: 'pg2tlmdgnl5h4-dev'
                  images: ${{ env.registryName }}/techboost/dotnetcoreapp:${{github.run_number}}

    deploytest:
  
          runs-on: ubuntu-latest
          needs: deploydev
          environment:
            name: test
            url: https://pg2tlmdgnl5h4-test.azurewebsites.net/
      
        
          steps:
              - name: 'Login via Azure CLI'
                uses: azure/login@v1
                with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}
        
              - uses: azure/webapps-deploy@v2
                with:
                  app-name: 'pg2tlmdgnl5h4-test'
                  images: ${{ env.registryName }}/techboost/dotnetcoreapp:${{github.run_number}}

    deployprod:
  
              runs-on: ubuntu-latest
              needs: deploydev
              environment:
                name: prod
                url: https://pg2tlmdgnl5h4-prod.azurewebsites.net/
          
            
              steps:
                  - name: 'Login via Azure CLI'
                    uses: azure/login@v1
                    with:
                      creds: ${{ secrets.AZURE_CREDENTIALS }}
            
                  - uses: azure/webapps-deploy@v2
                    with:
                      app-name: 'pg2tlmdgnl5h4-prod'
                      images: ${{ env.registryName }}/techboost/dotnetcoreapp:${{github.run_number}}